apiVersion: v1
kind: Pod
metadata:
  name: termination-demo
spec:
  terminationGracePeriodSeconds: 30 # The value zero indicates stop immediately; Defaults to 30 seconds.
  containers:
    - name: lifecycle-demo-container
      image: nginx