apiVersion: v1
kind: Pod
metadata:
  name: with-tolerations-demo
  labels:
    env: test
spec:
  nodeName: kbadmnode1
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
  tolerations:
    - key: "team1"
      operator: "Exists"
      effect: "NoSchedule"
