apiVersion: v1
kind: ConfigMap
metadata:
  name: maria-cm

data:
  DATABASE: "db"
  USER: "wp"
  PASSWORD: "123"
  ROOT_PASSWORD: "123"

---
apiVersion: v1
kind: Pod
metadata:
  name: maria-pod
  labels:
    app: wordpress
    role: database

spec:
  containers:
    - image: mariadb:10
      name: maria
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3306

      envFrom:
        - prefix: "MARIADB_"
          configMapRef:
            name: maria-cm
      resources:
        limits:
          memory: 500Mi
          cpu: 500m
        requests:
          memory: 100Mi
          cpu: 100m

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: maria-svc
spec:
  ports:
    - name: mariadb
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: wordpress
    role: database
  type: ClusterIP
