apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-cm

data:
  # HOST: "172.17.0.5" # maria-pod 的ip地址
  HOST: "worldpress.maria-svc"
  USER: "wp"
  PASSWORD: "123"
  NAME: "db"

---
apiVersion: v1
kind: Pod
metadata:
  name: wp-pod
  labels:
    app: wordpress
    role: website

spec:
  containers:
    - image: wordpress:5
      name: wp-pod
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80

      envFrom:
        - prefix: "WORDPRESS_DB_"
          configMapRef:
            name: wp-cm

      resources:
        limits:
          memory: 500Mi
          cpu: 500m
        requests:
          memory: 100Mi
          cpu: 100m

---

