apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template: # Pod template
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: web-demo
          image: nginx
          ports:
            - containerPort: 8080 # 定义containerPorts的目的纯粹是为了记录，实际暴露的还是80
              protocol: TCP
