apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  restartPolicy: Never
  volumes:
    - name: shared-data
      hostPath:
        path: /data
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
    - name: busybox-container
      image: busybox
      volumeMounts:
        - name: shared-data
          mountPath: /pod-data
      args:
        [
          "echo Hello from the debian container > /pod-data/index.html && sleep 600",
        ]
