apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  restartPolicy: Never
  volumes:
    - name: shared-data
      hostPath:
        path: /data
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
    - name: centos-container
      image: centos:7.9
      volumeMounts:
        - name: shared-data
          mountPath: /pod-data
      command:
        - /bin/sh
      args:
        - -c
        - echo Hello from the debian container > /pod-data/index.html; sleep 600
