apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  restartPolicy: Never
  volumes:
    - name: shared-data
      hostPath:
        path: /data
  containers:
    - name: nginx-container
      image: bitnami/nginx:1.23-debian-11
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
    - name: centos-container
      image: centos:7.9.2009
      volumeMounts:
        - name: shared-data
          mountPath: /pod-data
      command:
        - /bin/sh
      args:
        - -c
        - echo Hello from the debian container > /pod-data/index.html; sleep 3600
